export const LOCATION_OPTIONS: Record<string, string[]> = {
  Kathmandu: [
    "Thamel",
    "New Road",
    "Durbar Marg",
    "Putalisadak",
    "Bagbazar",
    "Ratnapark",
    "Baneshwor (New)",
    "Baneshwor (Old)",
    "Koteshwor",
    "Kalanki",
    "Balaju",
    "Chabahil",
    "Maharajgunj",
    "Boudha",
    "Kapan",
    "Gongabu",
    "Sitapaila",
    "Thankot",
    "Tokha",
    "Mulpani",
    "Sundarijal",
    "Tahachal",
  ],
  Lalitpur: [
    "Patan Durbar Square",
    "Lagankhel",
    "Pulchowk",
    "Jawalakhel",
    "Kumaripati",
    "Satdobato",
    "Gwarko",
    "Sanepa",
    "Ekantakuna",
    "Imadol",
    "Tikathali",
    "Lubhu",
    "Godawari",
    "Chapagaun",
  ],
  Bhaktapur: [
    "Bhaktapur Durbar Square",
    "Taumadhi",
    "Dattatreya",
    "Suryabinayak",
    "Thimi (Madhyapur Thimi)",
    "Balkot",
    "Jagati",
    "Nagarkot",
    "Sipadol",
    "Tathali",
  ],
};

export const CITIES = Object.keys(LOCATION_OPTIONS);
